### ISSUE TITLE
Wireframe shader error

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/com.xrtk.core#686]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

```
Shader error in 'Mixed Reality Toolkit/Wireframe': unrecognized identifier 'DEFAULT_UNITY_VERTEX_OUTPUT_STEREO_EYE_INDEX' at line 47 (on gles3)
```

## To Reproduce

1. Open XRTK.Core project
2. Switch to the Android build target
3. Build

## Expected behavior

No errors when building

## Actual behavior

Build error

**Comment by FejZa** [comment]
This is an interesting one. I run into it occasionally as well when building for Android. Fun thing is, that simply retrying the build will then succeed for me and the error is gone.

**Comment by StephenHodgson** [comment]
The error only shows once bc of the way unity reports the shader errors

**Comment by StephenHodgson** [comment]
If you closed the editor and opened it again, then did another build it'd likely show up again

**Comment by FejZa** [comment]
Makes sense. It doesn't show up every time I restart the editor though. I haven't nailed down to what action seems to reset the error.

**Comment by StephenHodgson** [comment]
Probably need to delete the library. temp, and obj cache as well.

**Comment by StephenHodgson** [comment]
It's all good, this will likely go away when we update to the Universal Rendering Pipeline

**Comment by FejZa** [comment]
Fixed in #732

**Comment by StephenHodgson** [comment]
Still seeing this error in the [CI/CD results](https://dev.azure.com/xrtk/Mixed%20Reality%20Toolkit/_build/results?buildId=5727&view=logs&j=0ab14b9f-e499-56d5-97b1-fd98b70ea339&t=859ff9fe-d969-518c-e56b-ea1c6c8313f3&l=785)
